### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/kwja#84]
## TODO

- [x] Change the repository name (kwja)
- [x] Provide a user-friendly CLI
- [x] Make pre-trained parameters available
  - [x] typo-base
  - [x] typo-large
  - [x] char-base
  - [x] char-large
  - [x] word-base (w/o discourse)
  - [x] word-large (w/o discourse)
  - [x] discourse-base
  - [x] discourse-large
- [x] Do an integration test on a large text corpus
- [x] Update README accordingly
